### ISSUE TITLE
Bad configuration transitions to RUNNING before jumping back to READY

### ISSUE THREAD

**Issue by teo** [FairRootGroup/FairMQ#109]
**Describe the bug**
When trying to transition from READY to RUNNING with a control plugin and a bad channel configuration, the device reports successfully entering RUNNING and then jumps back to READY.
The bad channel configuration to reproduce this issue is no config file, no command line parameters, but chan.foo.bar properties pushed to configuration from the plugin.

**To Reproduce**
FairMQ 1.2.7, 1-n-1 example, ALICE O² Control plugin

**Expected behavior**
Expected behavior would be staying in READY, or transitioning to ERROR, and in any case not declaring having entered RUNNING if the configuration is bad.

**Logs / Screenshots**
```
time="2018-10-29T15:52:21Z" level=info msg="[15:52:21][STATE] Entering RUNNING state" prefix=task-stdout task="fairmq-ex-1-n-1-processor#134ae150-db8c-11e8-865a-a08cfdc880fc"
time="2018-10-29T15:52:21Z" level=info msg="[15:52:21][INFO] DEVICE: Running..." prefix=task-stdout task="fairmq-ex-1-n-1-processor#134ae150-db8c-11e8-865a-a08cfdc880fc"
time="2018-10-29T15:52:21Z" level=info msg="[15:52:21][ERROR] out of range: _Map_base::at" prefix=task-stdout task="fairmq-ex-1-n-1-processor#134ae150-db8c-11e8-865a-a08cfdc880fc"
time="2018-10-29T15:52:21Z" level=info msg="[15:52:21][ERROR] incorrect/incomplete channel configuration?" prefix=task-stdout task="fairmq-ex-1-n-1-processor#134ae150-db8c-11e8-865a-a08cfdc880fc"
time="2018-10-29T15:52:21Z" level=info msg="[15:52:21][STATE] RUNNING state finished without an external event, entering READY state" prefix=task-stdout task="fairmq-ex-1-n-1-processor#134ae150-db8c-11e8-865a-a08cfdc880fc"
```

**System information (please complete the following information):**
 - OS: CC7
 - Compiler: whatever aliBuild uses, doesn't seem to matter

**Comment by dennisklein** [comment]
Thank you for your bug report. After looking into it, I can explain what happens: The out of range error is produced only when the device has already entered the RUNNING state. Most likely in your `Run()`, `Send/Receive()` is called, which tries to use the specified channel which does not exist.

=> Transitioning to READY here is definitely a bug. Also, we should improve on the error message. @rbx Maybe we can also introduce some config sanity checks at the end of `INIT DEVICE`. But not sure, what to check for. Number of channels > 0?

**Comment by rbx** [comment]
Fix is now in the dev.
