### ISSUE TITLE
DDS plugin: Fix unbounded growth of state-changes subscribers if clients fail to unsubscribe

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/FairMQ#190]
If a client subscribes to state-changes and fails to unsubscribe (e.g. due to an exception), their subscriptions will never expire which leads to meaningless custom commands sent out with no receiver. We need some way to expire such subscriptions.

**Comment by dennisklein** [comment]
@AnarManafov Is there a way to know for a custom command sender, if their message is internally discarded by DDS, because the recipient no longer exists?

**Comment by AnarManafov** [comment]
@dennisklein , it is a difficult question in terms of implementation.

Look, a custom command passes multiple actors before it reaches the destination: 
Intercom API -> Commander -> Agent -> Intercom API
Since we are in an async environment, at any of this stage the recipient can go away. It will be too complicated for DDS to track the entire chain and confirm whether the command has been delivered or not.  Consider also the fact that the actual CC will be split on on multiple commands as it can have multiple recipients - it makes it even more difficult to track it down.  

On top of that, it is very difficult in general to track whether the command is read from Intercom. Intercom uses a shared memory queue (for multiple reasons) and it is not even possible to detect that the other end is disconnected.
This is why agents automatically drain Intercom queues on task done events.

One thing DDS guarantees is that a given CC will be definitely delivered if the recipient is still subscribed.

I guess, a possible solution would be if a user implements commands with confirmations on top of DDs' CC. 
Also subscribing on CIntercomService::subscribeOnTaskDone will help to track potential recipients who went away.

**Comment by dennisklein** [comment]
@AnarManafov thx for the explanation.

@rbx So, basically, I see two remaining options:
1. Send subscription keepalive messages from the subscriber and implement a timeout on the plugin side.
2. Confirm each change state update and auto unsubscribe on missing confirmation.

Any other idea?

**Comment by rbx** [comment]
>     1. Send subscription keepalive messages (seldomly, like every couple of minutes) from the subscriber and implement a timeout on the plugin side.
> 
>     2. Confirm each change state update and auto unsubscribe on missing confirmation.
> 
> 
> Any other idea?

I think 1. is enough. It is rare that we have more than one subscriber for state changes, and if they politely unsubscribe there is no issue. I feel the amount of traffic 2. would add is not worth it.

**Comment by dennisklein** [comment]
> > ```
> > 1. Send subscription keepalive messages (seldomly, like every couple of minutes) from the subscriber and implement a timeout on the plugin side.
> > 
> > 2. Confirm each change state update and auto unsubscribe on missing confirmation.
> > ```
> > 
> > 
> > Any other idea?
> 
> I think 1. is enough. It is rare that we have more than one subscriber for state changes, and if they politely unsubscribe there is no issue. I feel the amount of traffic 2. would add is not worth it.

Agreed.

**Comment by dennisklein** [comment]
The heartbeat subscription to track the lifetime of devices we should just remove. I used it two years ago for a demo together with the O2 debug gui but it would be way too expensive for production scale (10 msg/s per device).

DDS provides now the task done event which should approximate the heartbeats subscription close enough. If process progress tracking will ever be needed, one should look into the developer story described in FairRootGroup/DDS#180 (last two posts).

**Comment by rbx** [comment]
Ok, I will remove the heartbeat subscriptions, besides your demo i don't think it is used anywhere.

@AnarManafov does the `CIntercomService::subscribeOnTaskDone` also trigger when a tool/external utility goes away, or is it only for tasks within the topology? If it did, we could use that as solution to unsubscribed a disappeared controller.

**Comment by AnarManafov** [comment]
@rbx , it's only for tasks in the topology.

In case of a EC. I think, devices and the control system are on the different design levels. I don't think it makes much sense for devices to know that a certain control went away. Maybe another EC will fire up and will take over the control on the existing devices. 
Also, the current design, as far as I know, the control system own DDS sessions. So, if it goes away, then sessions will be shutdown automatically, thus devices will receive TERM followed by a KILL. 

We also thinking about adding so called a "virtual" task to DDS. A virtual task can be any executable outside of a given topology. But it can register on DDS commander as a task and will be treated by DDS as a task. So, in case if this virtual task shuts down (disconnects), DDS will send a normal TaskDone event to all tasks. But this feature is not yet finalised and still in early design. We are trying to justify the need for it.

**Comment by dennisklein** [comment]
> Also, in the current design, as far as I know, the control system owns DDS sessions. So, if it goes away, then sessions will be shutdown automatically, thus devices will receive TERM followed by a KILL.

That's true for ECs like ODC. But in general, the FairMQ SDK also supports to terminate the controll process without terminating the DDS session (non-owning EC if you want). See e.g. usage of the `fairmq-dds-command-ui` utility we provide: https://github.com/FairRootGroup/FairMQ/blob/3785fd9ff9e61b407456b070058bd2d49a1db7fa/examples/dds/fairmq-start-ex-dds.sh.in#L55-L69

Another example for a non-owning EC will be the future `fairmq-top` utility which will provide a top-like table view on a running topology.

**Comment by AnarManafov** [comment]
Even in those cases, do you think devices are on the same level and need to know that external "top" utility went away?

**Comment by dennisklein** [comment]
> Even in those cases, do you think devices are on the same level and need to know that external "top" utility went away?

In `fairmq-dds-command-ui -c x -w "DEVICE READY"` `-c x` triggers a certain change state on all devices in the topology (custom command) and `-w "DEVICE_READY"` means block until all devices are in state `DEVICE READY`. The latter is implemented by `fairmq-dds-command-ui` sending a custom command "SUBSCRIBE TO STATE CHANGES" to all devices which will add its dds channel ID to a list of subscribers. On a state change every device will send out a custom command with that event info to all subscribers. If everything goes normal, before `fairmq-dds-command-ui` exits, it will send a `UNSUBSCRIBE FROM STATE CHANGES` custom command. If it exits abnormally, because it is sigkilled or network connection is cut etc. it will stay subscribed and devices will forever notify this no longer meaningful channel ID about state changes. Same for the top-like utility. This is what this issue is all about.

You can think of it like this: we want to implement an observer protocol over custom commands and are thinking about how to handle situations where the clients disconnect abnormally. It is solvable without, but since custom commands is a service by DDS, our thinking was, maybe we can get the disconnect events directly from the source for efficiency.
