### ISSUE TITLE
FairMQ device failed to change a state using FairMQ.SDK

### ISSUE THREAD

**Issue by AndreyLebedev** [FairRootGroup/FairMQ#206]
**Describe the bug**
The DDS topology is started using DDS-control on a new Slurm cluster (`lxbk0595`). DDS-control hangs (or timeded out) trying to run `ConfigureRun` request (`.config` option of `sample-client`). Internally `dds-control-server` uses fair::mq::sdk::Topology::AsyncChangeState method to update the states of the devices in the topology.  Devices successfully updated to INIT DEVICE and COMPLETE INIT states but failed in the BIND state. 

From the device's logs we can see the following errors:
```
Error on handling DDS property update for data2: value=tcp://10.20.4.106:22497, senderTaskID=9051258523765084712: _Map_base::at
```

This is an exception in [fair::mq::plugins::DDS::SubscribeForConnectingChannels](https://github.com/FairRootGroup/FairMQ/blob/3f5374820a56c472a79e81b977861eddf4bff343/fairmq/plugins/DDS/DDS.cxx#L239)

For Sampler and Sink there is a different error in the logs:
```
[ERROR] Failed binding socket main/ProcessorGroup/ExCol_2/Sink_0.data2[0].pull, reason: Permission denied
```
But it looks like Sink and Sampler were able to recover.

**To Reproduce**
The test was done on a new Slurm cluster. You can login to it via interactive node `lxbk0595`.
DDS control is installed in `/lustre/rz/andrey/Soft/centos/DDS-control/install/`.
Run DDS control server:
```bash
bin/dds-control-server -r slurm -c /lustre/rz/andrey/test_slurm_job.sh 
```
Run client:
```bash
bin/sample-client --topo /lustre/rz/andrey/ex-dds-topology-infinite.xml 
```
The topology and Slurm config file you can see in the command options.

**Logs / Screenshots**
Full logs of the run can be found in `/lustre/rz/andrey/.DDS/sessions/950df43d-ca72-4655-a3dd-5ea1a209ddb5/2019-09-12-16-54-37`

`grep "\[ERROR\]" 2976_*/*.log` gives exact file names and line numbers with the error.

**System information (please complete the following information):**
 - OS: CentOS Linux 7 
 - Compiler: GCC 8.3.0
 - Environment: custom installation in `/lustre/rz/andrey/Soft/centos`

**Comment by rbx** [comment]
The issue is that DDS plugin receives more than one message per connecting channel, which is not what the device expects for its channels in this case. Looking at the topology file this is because the properties are not scoped to collections.

As discussed, we will improve the error message in the plugin and the SDK.

Meanwhile you can scope the properties to collections and this should resolve the issue from you.

**Comment by AndreyLebedev** [comment]
After the latest changes in the FairMQ [e3890a4](https://github.com/FairRootGroup/FairMQ/commit/e3890a40339e3726c59604eb14f95c2b5ba03bd8) and setting the property scope to "collection" I was able to run the test.

**Comment by rbx** [comment]
Ok, great!
I'll keep this open until we improve the error notifications.
