### ISSUE TITLE
Zombie `fairmq-shmmonitor` processes not being reaped?

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/FairMQ#216]
We have the impression that whenever there is something making `fairmq-shmmonitor` crash, there is nothing which actually handles the SIGCHLD and the processes end up as zombies. Would it be possible to add some sort of reaper logic, or is this something which you expect the device implementor to do?

**Comment by rbx** [comment]
We make monitor a daemon, which will let it crash or be killed without problem. But it looks like we were not fully detaching the monitor from the parent in the current code in the dev. I just submitted a fix that should fix this, please try it when it is merged (or before).

But what would be more interesting to know, is why is the monitor crashing at all for you. It shouldn't crash. Can you give more details?

**Comment by ktf** [comment]
I guess that happens as part of specifying both `--transport` and `transport=shmem`.

**Comment by ktf** [comment]
This is now  understood.
