### ISSUE TITLE
FairMQ leaves behind ipc files?

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/FairMQ#222]
It looks like whenever I use "ipc://foo" for a channel, the file "foo" is left behind in the current user directory. Is that expected?

**Comment by ktf** [comment]
@matthiasrichter

**Comment by rbx** [comment]
It is expected, this is what ZeroMQ chooses to do for ipc files (https://github.com/zeromq/libzmq/issues/3204). Is it problematic for you?

**Comment by ktf** [comment]
I guess we should then create them in /tmp?

**Comment by rbx** [comment]
From my experience, reusing these files across multiple runs has no problem, but just to keep it clean, sure. You can control it via the channel address, e.g.: `--channel-config name=data,method=bind,type=pub,address=ipc:///tmp/bla`.

**Comment by ktf** [comment]
Thanks.
