### ISSUE TITLE
Can't recreate fair::mq::sdk::Topology object for the same DDS session

### ISSUE THREAD

**Issue by AndreyLebedev** [FairRootGroup/FairMQ#239]
**Describe the bug**
Can't recreate fair::mq::sdk::Topology object for the same DDS session. This functionality is required in the ODC in order to implement a topology update command.

The reason is that fair::mq::sdk::Topology stores fair::mq::sdk::DDSSession which it gets in the constructor using `std::move`. In this case the scope of the fair::mq::sdk::DDSSession object is the same as the scope of the fair::mq::sdk::Topology itself. When fair::mq::sdk::Topology is destroyed the session object is also destroyed.

**To Reproduce**

1. Create DDS session. 
2. Create fair::mq::sdk::Topology with the session. 
3. Destroy fair::mq::sdk::Topology. 
4. Create another fair::mq::sdk::Topology with the same session.

**Expected behavior**
The design of the fair::mq::sdk::Topology has to be implemented in a way that the user defines the scope of the DDS session but not the fair::mq::sdk::Topology itself.

**Comment by AndreyLebedev** [comment]
Closing the issue. The problem was related to misusing the `fair::mq::sdk` API. 

As a suggestion, I would recommend adding a topology update functionality to fair::mq::sdk::Topology.

**Comment by dennisklein** [comment]
> As a suggestion, I would recommend adding a topology update functionality to fair::mq::sdk::Topology.

Yes, we agree, this will be the superior solution. We will add it in the near future, #240.
