### ISSUE TITLE
Disable allow_guessing when parsing boost options

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/FairMQ#268]
We recently introduced a change in DPL which would have removed the "allow_guessing" style for boost::program_options. While this worked fine on our side, it breaks when passing (certain) options to FairMQ, because on its side FairMQ still uses "allow_guessing". We reverted the change (and renamed one of the options to avoid conflicts) however IMHO it would be better if FairMQ disabled the allow_guessing style as well, so that we can disable it on our side (or at least provide an option to do so). For the record the incriminated option is `--config` which conflicts with `--config-key`. Any idea?

**Comment by dennisklein** [comment]
I believe we can disable the *allow_guessing* behaviour. (didn't even know it existed) @rbx any objections?

**Comment by rbx** [comment]
Sounds good to me, let's disable it

**Comment by ktf** [comment]
To disable it in DPL we do the opposite of 

https://github.com/AliceO2Group/AliceO2/pull/3646/files

**Comment by ktf** [comment]
https://github.com/AliceO2Group/AliceO2/pull/3646/files#diff-4de37a90081a5dc6cb4bfa71261f841aL1569-L1581 is the relevant bit.

**Comment by dennisklein** [comment]
available in `v1.4.18` (together with #267)
