### ISSUE TITLE
New message from SHMEM UR check

### ISSUE THREAD

**Issue by ironMann** [FairRootGroup/FairMQ#272]
**Describe the bug**
The logical condition enables user to create a message with any address.

**To Reproduce**
Create a message from unmanaged SHMEM region with an address outside of the said region.

**Expected behavior**
exception thrown

**Logs / Screenshots**
https://alice.its.cern.ch/jira/browse/O2-1459

**System information (please complete the following information):**
 - OS: [e.g. MacOS 10.13, Fedora 28, Ubuntu 14.04]
 - Compiler: [e.g. GCC 8.1, Clang 3.5]
 - Environment: [e.g. FairSoft version, alfadist revision]

**Additional context**
https://github.com/FairRootGroup/FairMQ/blob/b5bb476b0da55bfd5b0b72f3da52afac194b865b/fairmq/shmem/Message.h#L112

The OR condition should be AND.

@rbx This causes downstream processes to fail when GetData() returns null. 

What is the general policy of FMQ. Should user check for nullptr returned by GetData() on a received message?

**Comment by rbx** [comment]
If the incoming message size is 0 (it is allow to send empty messages) then `GetData` should return `nullptr`, otherwise it should be a valid pointer.

**Comment by rbx** [comment]
Fixed in the dev branch.
