### ISSUE TITLE
Add UNDEFINED state to fair::mq::sdk::DeviceState enum

### ISSUE THREAD

**Issue by AndreyLebedev** [FairRootGroup/FairMQ#286]
I've already briefly discussed this issue with Alexey. Just want to document it here so that it's not get lost.

**Is your feature request related to a problem? Please describe.**

The idea is to add an UNDEFINED or UNKNOWN or NONE state to fair::mq::sdk::DeviceState enum.
Some use cases:
1) I'm using directly DeviceState enum in my code. What would be a default value to a variable of type DeviceState? Before getting any information from the device the state is technically unknown.
2) The return value from a function when a state can't be retrieved.
3) DeviceState enum is also used to return an aggregated state of the topology. Consider a case when the topology is in a mixed state. There is no single state in this case, for me, the state is also undefined.

**Comment by dennisklein** [comment]
> 1. I'm using directly DeviceState enum in my code. What would be a default value to a variable of type DeviceState? Before getting any information from the device the state is technically unknown.
> 2. The return value from a function when a state can't be retrieved.

:+1: I support adding a "sentinel" value to the `fair::mq::sdk::DeviceState` enum (which is essentially `fair::mq::State`) - I like `fair::mq::State::Undefined`.

> 3. DeviceState enum is also used to return an aggregated state of the topology. Consider a case when the topology is in a mixed state. There is no single state in this case, for me, the state is also undefined.

For this last example, I think, `Undefined` does not fit though. In the [`DeviceState AggregateState(TopologyState)`](https://github.com/FairRootGroup/FairMQ/blob/78b1c188bfb6158a7c1a8db2745a88099dff19da/fairmq/sdk/Topology.h#L103-L114) helper we opted to not map this case at all and instead throw. I see two options, either
1. add a `AggregateTopologyState` enum that also has a value `Mixed` or similar, or
2. - if we want to be fancy - use the optional template, e.g. [`std::optional<DeviceState>`](https://en.cppreference.com/w/cpp/utility/optional) or `boost::optional<DeviceState>` for return values in contexts where exceptions cannot be used and need to be mapped to a scalar.

**Comment by AndreyLebedev** [comment]
> For this last example, I think, `Undefined` does not fit though. In the [`DeviceState AggregateState(TopologyState)`](https://github.com/FairRootGroup/FairMQ/blob/78b1c188bfb6158a7c1a8db2745a88099dff19da/fairmq/sdk/Topology.h#L103-L114) helper we opted to not map this case at all and instead throw. I see two options for return values in contexts where exceptions cannot be used and need to be mapped to a scalar, either
> 
> 1. add a `AggregateTopologyState` enum that also has a value `Mixed` or similar (<- I personnally favour this), or
> 2. _if we want to be fancy_ - use the optional template, e.g. [`std::optional<DeviceState>`](https://en.cppreference.com/w/cpp/utility/optional) or `boost::optional<DeviceState>`.

I agree that an aggregated topology state is a different case.

I have no problem if  [`DeviceState AggregateState(TopologyState)`](https://github.com/FairRootGroup/FairMQ/blob/78b1c188bfb6158a7c1a8db2745a88099dff19da/fairmq/sdk/Topology.h#L103-L114) throws an exception. It can be treated in the code. But a nonthrowing version of this function would be also useful. For instance, as in ODC we have to send the result back via gRPC, so there must be a value. I think if it's defined in FairMQ is much better than ODC invents its own enum. So I vote for an `AggregateTopologyState` enum.

**Comment by dennisklein** [comment]
see https://github.com/FairRootGroup/FairMQ/pull/287#issuecomment-658772514
