### ISSUE TITLE
Implement GetStateName and GetState functions for AggregatedTopologyState

### ISSUE THREAD

**Issue by AndreyLebedev** [FairRootGroup/FairMQ#291]
**Describe the solution you'd like**

There are two convenient functions `string GetStateName(const State state)` and `State GetState(const string& state)` for the `fair::mq::State` which are missing for the new `fair::mq::AggregatedTopologyState`. It would be great to have the same functionality also for the `fair::mq::AggregatedTopologyState`.

**Comment by dennisklein** [comment]
Added via b5545c1575a8dd97cc76ae66dd6bb0fa7324a1d0
