### ISSUE TITLE
Improve `--channel-config` syntax

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/FairMQ#337]
I've received several reports that --channel-config syntax is confusing, due to the fact that `name=channel-name` is not really an assignment, but a selector of the channel a given configuration applies to. Would it be possible to have something like:

```
--channel-config my-channel-name:address=127.0.0.1:8080,...
```

which would be the equivalent of:

```
--channel-config name=my-channel-name,address=127.0.0.1:8080,...
```
?

**Comment by dennisklein** [comment]
Sure, we would accept such a PR, provided that the current syntax keeps working (there are a lot of usages out there which we cannot easily catch and transform).

**Comment by ktf** [comment]
#340 should do the trick.

**Comment by dennisklein** [comment]
Will make it into next patch release.
