### ISSUE TITLE
Use list(APPEND CMAKE_MODULE_PATH ...) instead of set(CMAKE_MODULE_PATH)

### ISSUE THREAD

**Issue by aphecetche** [FairRootGroup/FairMQ#342]
in the top CMakeLists.txt.

AFAIK hard-setting the CMAKE_MODULE_PATH in the CMakeLists.txt instead of appending to it is not a good strategy... 
For instance it forces people trying to provide a Conan recipe for FairMQ to patch the CMakeLists.txt before starting any build :wink: 

(apply also to FairRoot and FairLogger btw)

**Comment by ChristianTackeGSI** [comment]
I wonder, whether it should be `list(APPEND)` or `list(PREPEND)`?

**Comment by dennisklein** [comment]
For FairRoot this is probably not yet fully applied, but @ChristianTackeGSI and I will keep it in mind. Let me know, if I overlooked anything in FairMQ or FairLogger.
