### ISSUE TITLE
Make unit tests usable for continuous integration: use dynamic port assignment

### ISSUE THREAD

**Issue by matthiasrichter** [FairRootGroup/FairMQ#380]
We have been running into problems with using unit tests in continuous integration because of the fixed ports being used in the configuration of the devices. Since the bind to a port switches dynamically to another port if the requested one is not free, the communication between devices is broken.

Possible solutions:
1) advanced: run the unit tests using DDS
2) switch off dynamic port bind and handle the failure by restarting the test with different ports
3) sequential start of devices, extract port binding from log message and start the connecting devices with this configuration

**Comment by rbx** [comment]
Besides the recently closed #75 (that will be implemented in the future in other ways), just wanted to make sure that the following is documented.

> 2. switch off dynamic port bind and handle the failure by restarting the test with different ports

Switching off the dynamic port bind is already possible since a while, by configuring a channel with `autoBind = false`. For example, via the `--channel-config`:

```
fairmq-bsampler --id b1 --channel-config name=data,method=bind,type=pub,address=tcp://*:5555,autoBind=false
```

**Comment by dennisklein** [comment]
Another way we work around this long-standing issue of not having a test runner with dynamic service discovery is to run the FairMQ test suite in its own network namespace (which only works on Linux - but mentioning it for completeness).

**Comment by dennisklein** [comment]
Test suite supports being run in parallel now for a while. Missed that we had an issue for it.
