### ISSUE TITLE
-DZeroMQ_ROOT=$ZEROMQ_ROOT is silently ignored if path not found

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/FairMQ#387]
**Describe the bug**

When building  zeromq with Cmake, which defaults to putting libraries in lib64, providing `-DZeroMQ_ROOT=$ZEROMQ_ROOT` seems to silently fail if zeromq is also available on the system.

**To Reproduce**
1. On linux
2. Instally zeromq on the system, making sure you have libzmq.so.6
3. Install zeromq in a separate folder, using cmake, ala-alibuild
4. Build FairMQ passing `-DZeroMQ_ROOT=$ZEROMQ_ROOT`

**Expected behavior**
I expect the build to fail, given I pass `-DZeroMQ_ROOT=$ZEROMQ_ROOT` and libzmq cannot be found there.
The build succeeds using the system version.

**Comment by dennisklein** [comment]
The behavior you observe is as designed by CMake, see https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure.

On a side note, FairMQ also looks up `$ZEROMQ_ROOT` environment variable (`<UPPERPKGNAME>_ROOT `). So, specifying `-DZeroMQ_ROOT=$ZEROMQ_ROOT` is just redundant in this case.

**Comment by dennisklein** [comment]
In the link above you can find various CMake options to disable system lookup. Unfortunately, AFAICS, there is no *disable system lookup* switch with **package level granularity**.

If a *per-package-no-system-lookup* feature is desired, let's move the discussion to the [FairCMakeModules](https://github.com/FairRootGroup/FairCMakeModules) repo as it meanwhile hosts the relevant CMake code used by FairMQ ([`find_package2`](https://fairrootgroup.github.io/FairCMakeModules/latest/module/FairFindPackage2.html#find-package2))
