### ISSUE TITLE
Reduce number of open file descriptors required by SHM transport

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/FairMQ#407]
Currently a FairMQ device requires 4+N+M file descriptors to work with shared memory, where M and N are the number of incoming and outgoing edges, and 4 is some files which seems to be always opened to map shared memory:
- fmq_XXX_m_0
- fmq_XXX_mng
- fmq_XXX_mtx 
- fmq_XXX_cv

Would it be possible to merge the 4 files into 1?

**Comment by rbx** [comment]
Possibly the 4 can be reduced to 2, but not 1.

Why?

**Comment by rbx** [comment]
Ok, reduction from 4 to 2 is definitely doable, I just did it. To 1 not.

**Comment by ktf** [comment]
Thanks. I think the worry is that we have to many open file descriptors, so we would like to minimise what is needed by the framework. I think 2 instead of 4 is more than enough.

**Comment by rbx** [comment]
Ok, I'll add the reduction to the next release.

**Comment by ktf** [comment]
Thanks. Any ETA for it? it would be good if it was sometimes this week.

**Comment by rbx** [comment]
This week should be fine.

**Comment by rbx** [comment]
4 has been reduced to 2. Closing this, as further reduction is not likely atm.

**Comment by ktf** [comment]
thanks that should do.

Ciao,
Giulio
