### ISSUE TITLE
Ports used during tests

### ISSUE THREAD

**Issue by dberzano** [FairRootGroup/FairMQ#47]
In our tests ([see here, CERN account required](https://ali-ci.cern.ch/repo/logs/AliceO2Group/AliceO2/1151/5edd71c92c407317dd0018229b3fa3e35086fd3a/build_o2_macos/fullLog.txt)) we have noticed that the `FairMQ.Protocols` test systematically fails on a macOS node.

Turns out, the test tries to listen to the TCP port `127.0.0.1:6000` which is also used by another process running independently on the same system (`X11.bin` for the record).

I don't know if it's possible to either automatically pick a different port at the beginning of the test (this would be ideal), or maybe hardcode a different port for the moment. For instance, [port 7654](https://www.speedguide.net/port.php?port=7654) seems to be a better candidate 😄

(cc'ing @dennisklein)

**Comment by dennisklein** [comment]
The ports are currently hardcoded in the file [test/protocols/config.json.in](../blob/dev/test/protocols/config.json.in). Quickest fix would be, if you modify the ones that break on your machine there and make a PR.

On midterm, we would like to improve the test runner also for other reasons (This would e.g. involve making all ports depending on a configurable base port, one can pass in at runtime via environment variable. Ideally we would need a lightweight DDS type of solution here, this would also help development/debugging of devices etc.)
