### ISSUE TITLE
Spurious (?) warning on startup

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/FairMQ#50]
Since I migrated to the split FairMQ I started to get:

```cpp
[WARN] FairMQProgOptions not available! Using defaults.
[WARN] FairMQProgOptions not available! Using defaults.
[WARN] FairMQProgOptions not available! Using defaults.
[WARN] FairMQProgOptions not available! Using defaults.
```

what is that about?

**Comment by rbx** [comment]
This happens if transport cannot find FairMQProgOptions. Please provide more detail on when this happens, or better a link to code that causes this.

**Comment by rbx** [comment]
Is it possible that you have added some code that uses `FairMQTransportFactory` without giving it FairMQProgOptions?
E.g.: this should give no warning:
https://github.com/FairRootGroup/FairMQ/blob/master/test/protocols/_push_pull_multipart.cxx#L34
, while this will produce the above warning:
https://github.com/AliceO2Group/AliceO2/blob/dev/DataFormats/MemoryResources/test/testMemoryResources.cxx#L24

**Comment by ktf** [comment]
Yes. For example `https://github.com/AliceO2Group/AliceO2/blob/dev/Framework/Core/test/test_DataRelayer.cxx`. Why is that a `warning` (which I interpret as something non fatal which should be fixed, as opposed to an `INFO`)? Can you change the level for that message?

**Comment by rbx** [comment]
Changed the level to debug. Transport has meaningful defaults if no FairMQProgOptions are given. You will need to provide it if you want to change the defaults.

**Comment by ktf** [comment]
Thanks. That's more than reasonable, I think.
