### ISSUE TITLE
Distinguish 'tracked' from 'untracked' config properties

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/FairMQ#6]
Currently, plugins can only modify config properties while the device is in `INIT_DEVICE` state. We need support for changing config properties with immediate effect regardless of device state.

**Comment by rbx** [comment]
note: Implement with `SetProperty`/`UpdateProperty`.

**Comment by teo** [comment]
We need to push a run number from the O² control plugin as a property in the `Ready` state, immediately before the `Run` transition. The reason for this is the fact that the run number might not be known during `Init device`, and indeed we might go from one run to the next without reconfiguring, just stopping and starting. Setting a property doesn't seem to be allowed in the `Ready` state right now. 
Could you please add `Ready` to the list of allowed states for `PluginServices::SetProperty`?

**Comment by dennisklein** [comment]
@teo The plugin interface finally learned some new interfaces that we planned long ago (in `dev`). Would be interesting to know, if the new bulk APIs `Get/SetProperties*` are useful to you.

```diff
diff --git a/fairmq/Plugin.h b/fairmq/Plugin.h
index 0984a38..9affec3 100644
--- a/fairmq/Plugin.h
+++ b/fairmq/Plugin.h
@@ -85,13 +85,30 @@ class Plugin
     // device config API
     // see <fairmq/PluginServices.h> for docs
     auto PropertyExists(const std::string& key) -> int { return fPluginServices->PropertyExists(key); }
+
     template<typename T>
-    auto SetProperty(const std::string& key, T val) -> void { fPluginServices->SetProperty(key, val); }
+    T GetProperty(const std::string& key) const { return fPluginServices->GetProperty<T>(key); }
     template<typename T>
-    auto GetProperty(const std::string& key) const -> T { return fPluginServices->GetProperty<T>(key); }
-    auto GetPropertyAsString(const std::string& key) const -> std::string { return fPluginServices->GetPropertyAsString(key); }
+    T GetProperty(const std::string& key, const T& ifNotFound) const { return fPluginServices->GetProperty(key, ifNotFound); }
+    std::string GetPropertyAsString(const std::string& key) const { return fPluginServices->GetPropertyAsString(key); }
+    std::string GetPropertyAsString(const std::string& key, const std::string& ifNotFound) const  { return fPluginServices->GetPropertyAsString(key, ifNotFound); }
+    fair::mq::Properties GetProperties(const std::string& q) const { return fPluginServices->GetProperties(q); }
+    fair::mq::Properties GetPropertiesStartingWith(const std::string& q) const { return fPluginServices->GetPropertiesStartingWith(q); };
+    std::map<std::string, std::string> GetPropertiesAsString(const std::string& q) const { return fPluginServices->GetPropertiesAsString(q); }
+    std::map<std::string, std::string> GetPropertiesAsStringStartingWith(const std::string& q) const { return fPluginServices->GetPropertiesAsStringStartingWith(q); };
+
     auto GetChannelInfo() const -> std::unordered_map<std::string, int> { return fPluginServices->GetChannelInfo(); }
     auto GetPropertyKeys() const -> std::vector<std::string> { return fPluginServices->GetPropertyKeys(); }
+
+    template<typename T>
+    auto SetProperty(const std::string& key, T val) -> void { fPluginServices->SetProperty(key, val); }
+    void SetProperties(const fair::mq::Properties& props) { fPluginServices->SetProperties(props); }
+    template<typename T>
+    bool UpdateProperty(const std::string& key, T val) { return fPluginServices->UpdateProperty(key, val); }
+    bool UpdateProperties(const fair::mq::Properties& input) { return fPluginServices->UpdateProperties(input); }
+
+    void DeleteProperty(const std::string& key) { fPluginServices->DeleteProperty(key); }
+
     template<typename T>
     auto SubscribeToPropertyChange(std::function<void(const std::string& key, T newValue)> callback) -> void { fPluginServices->SubscribeToPropertyChange<T>(fkName, callback); }
     template<typename T>
```

**Comment by teo** [comment]
> @teo The plugin interface finally learned some new interfaces that we planned long ago (in `dev`). Would be interesting to know, if the new bulk APIs `Get/SetProperties*` are useful to you.
> 

Hi @dennisklein, looks good! I haven't tried it yet but I appreciate the bulk {Get,Set}Properties, and the overall behavior that allows pushing values at any time.
Are there API docs for this? If not, could you please clarify the difference between SetPropert{y,ies} and UpdatePropert{y,ies}?

**Comment by dennisklein** [comment]
> Are there API docs for this?

Not yet.

> If not, could you please clarify the difference between SetPropert{y,ies} and UpdatePropert{y,ies}?

`void SetPropert{y,ies}(...)` will succeed to create a new key even if it was not declared before e.g. via a command line option.

`bool UpdatePropert{y,ies}(...)` will return false if the key does not exist yet. The bulk version will return false if a single key in the given argument set does not exist and not set any value (even the ones that exist).

**Comment by dennisklein** [comment]
> and the overall behavior that allows pushing values at any time.

We also need to add a section to our docs listing when certain device properties are being applied. Some are tied to the state machine (e.g. setting/updating channel properties during `RUNNING` state is possible but will not trigger any state changes, only when a controller transitions to `INITIALIZING DEVICE`, some might be effective immediately.
