### ISSUE TITLE
Disable rate logging

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/FairMQ#88]
I could not find any way to disable the rate logging. Is there one? If not, could it be added?

**Comment by rbx** [comment]
If you use `--channel-config`, you can say:
`--channel-config name=data,type=push,method=bind,address=tcp://*:5555,rateLogging=0`
if you use JSON you say:
```json
...
                        "sockets": [
                            {
                                "type": "push",
                                "method": "bind",
                                "address": "tcp://*:5555",
                                "sndBufSize": 1000,
                                "rcvBufSize": 1000,
                                "rateLogging": 0
                            }
                        ]
```
You can see it in use in most of our examples.

**Comment by ktf** [comment]
I meant programmatically from the FairMQDevice API, but indeed what you propose might also work.

**Comment by rbx** [comment]
edited my comment at the same time with your followup question :)

**Comment by ktf** [comment]
Ah, ok, so it's a property of the channel, not of the device. Understood.
