### ISSUE TITLE
Option to compile static FairMQ library

### ISSUE THREAD

**Issue by mpapenbrock** [FairRootGroup/FairMQ#89]
I would like to create Docker images my individual FairMQ services, e.g. a sample, a processor, etc. In order to reduce the image size, it would be favourable to compile the service into a static executable which can is then copied into a minimal base image and does not require further dependencies. As far as I am aware, static libraries are needed to achieve that.

An option to compile to compile FairMQ (and by extension FairLogger) into a static library would help to solve this issue.

**Comment by dennisklein** [comment]
I will need to investigate, if this can be done, because FairMQ depends on a number of external libraries which are usually only installed as shared libraries. I will get back to you within the week.

In any case, in order to reduce disk space, make sure you compile FairMQ without debug symbols, e.g. `-DCMAKE_BUILD_TYPE=Release`.

**Comment by dennisklein** [comment]
https://github.com/FairRootGroup/FairLogger/releases/tag/v1.3.0

**Comment by dennisklein** [comment]
Another flag you might want to control is `-fPIC` (on by default). In FairMQ `v1.3.2` you will be able to use `-DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=OFF` to switch it off, i not desired.

**Comment by dennisklein** [comment]
[FairMQ `v1.3.2`](https://github.com/FairRootGroup/FairMQ/releases/tag/v1.3.2) is now available for testing.

**Comment by mpapenbrock** [comment]
I have tested the solution, and I cannot see any issues on the FairMQ side. However, I am getting some undefined references in the static version of the zmq library. I do not believe this has anything to do with FairMQ, and will need some further investigation on my side first.
I think this issue can be closed. Thank you for the effort!
