### ISSUE TITLE
Shmem permission denied

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/FairMQ#98]
**Describe the bug**
@Barthelemy reported to me, he sees `permission denied`, when running our shm examples. It is not yet understood, if it is his environment or something we can handle on FairMQ side.

**To Reproduce**
In build directory, run
* `./fairmq/fairmq-shmmonitor -c` and
* `ctest -V -R 'Example-1-1-shmem'`.

**Expected behavior**
Examples should execute successfully.

**Logs / Screenshots**
[log.txt](https://github.com/FairRootGroup/FairMQ/files/2461710/log.txt)

**System information (please complete the following information):**
 - OS: MacOS
 - Compiler: Apple Clang
 - Environment: alidist

**Comment by Barthelemy** [comment]
Hi, 
if you need access to the machine, let me know. I am also available for extra information. 
Cheers,

**Comment by rbx** [comment]
Thanks for the report.

The failing tests do not set a unique session ID and only use the default one. Looks like some other user on the system also has FairMQ devices with shmem running (or hanging, or failed cleanup), so the tests fail to access shmem objects with the same names.

We will:
- add unique sessions IDs to the 5 failing tests.
- include user ID in the shmem object names, which will allow different users to run things even with the same session ID.

**Comment by dennisklein** [comment]
@Barthelemy Thank you for helping to improve FairMQ! We believe your issue has been resolved in release `v1.3.4`. Reopen or create a new issue, if we missed anything.
